name: Bug report
about: Report a Cloudbox bug
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      render: shell
